In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [3]:
# Load the iris dataset
data = load_iris()
X = data.data
y = data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# Initialize weights and bias
weights = np.zeros(X_train.shape[1])
bias = 0

# Set learning rate and number of iterations
learning_rate = 0.01
iterations = 1000

In [5]:
# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Logistic Regression
for i in range(iterations):
    # Forward propagation
    z = np.dot(X_train, weights) + bias
    y_pred_train = sigmoid(z)
    
    # Backward propagation
    dw = (1 / len(X_train)) * np.dot(X_train.T, (y_pred_train - y_train))
    db = (1 / len(X_train)) * np.sum(y_pred_train - y_train)
    
    # Update weights and bias
    weights -= learning_rate * dw
    bias -= learning_rate * db

In [6]:
# Predict on the test set
y_pred_test = sigmoid(np.dot(X_test, weights) + bias)
y_pred_test = [1 if p > 0.5 else 0 for p in y_pred_test]

In [7]:
# Print confusion matrix, sensitivity, specificity
cm = confusion_matrix(y_test, y_pred_test)
print('Confusion Matrix:')
print(cm)
sensitivity = cm[0, 0] / (cm[0, 0] + cm[0, 1])
print('Sensitivity : ', sensitivity )
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
print('Specificity : ', specificity)

Confusion Matrix:
[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Sensitivity :  0.0
Specificity :  1.0
